/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace PolyVoxCore {

using System;
using System.Runtime.InteropServices;

public class LodRecordVector : IDisposable, System.Collections.IEnumerable
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IEnumerable<LodRecord>
#endif
 {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LodRecordVector(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(LodRecordVector obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~LodRecordVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PolyVoxCorePINVOKE.delete_LodRecordVector(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public LodRecordVector(System.Collections.ICollection c) : this() {
    if (c == null)
      throw new ArgumentNullException("c");
    foreach (LodRecord element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public LodRecord this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array)
#else
  public void CopyTo(LodRecord[] array)
#endif
  {
    CopyTo(0, array, 0, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array, int arrayIndex)
#else
  public void CopyTo(LodRecord[] array, int arrayIndex)
#endif
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(int index, System.Array array, int arrayIndex, int count)
#else
  public void CopyTo(int index, LodRecord[] array, int arrayIndex, int count)
#endif
  {
    if (array == null)
      throw new ArgumentNullException("array");
    if (index < 0)
      throw new ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

#if !SWIG_DOTNET_1
  System.Collections.Generic.IEnumerator<LodRecord> System.Collections.Generic.IEnumerable<LodRecord>.GetEnumerator() {
    return new LodRecordVectorEnumerator(this);
  }
#endif

  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return new LodRecordVectorEnumerator(this);
  }

  public LodRecordVectorEnumerator GetEnumerator() {
    return new LodRecordVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class LodRecordVectorEnumerator : System.Collections.IEnumerator
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IEnumerator<LodRecord>
#endif
  {
    private LodRecordVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public LodRecordVectorEnumerator(LodRecordVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public LodRecord Current {
      get {
        if (currentIndex == -1)
          throw new InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new InvalidOperationException("Collection modified.");
        return (LodRecord)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new InvalidOperationException("Collection modified.");
      }
    }

#if !SWIG_DOTNET_1
    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
#endif
  }

  public void Clear() {
    PolyVoxCorePINVOKE.LodRecordVector_Clear(swigCPtr);
  }

  public void Add(LodRecord x) {
    PolyVoxCorePINVOKE.LodRecordVector_Add(swigCPtr, LodRecord.getCPtr(x));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = PolyVoxCorePINVOKE.LodRecordVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = PolyVoxCorePINVOKE.LodRecordVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    PolyVoxCorePINVOKE.LodRecordVector_reserve(swigCPtr, n);
  }

  public LodRecordVector() : this(PolyVoxCorePINVOKE.new_LodRecordVector__SWIG_0(), true) {
  }

  public LodRecordVector(LodRecordVector other) : this(PolyVoxCorePINVOKE.new_LodRecordVector__SWIG_1(LodRecordVector.getCPtr(other)), true) {
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public LodRecordVector(int capacity) : this(PolyVoxCorePINVOKE.new_LodRecordVector__SWIG_2(capacity), true) {
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  private LodRecord getitemcopy(int index) {
    LodRecord ret = new LodRecord(PolyVoxCorePINVOKE.LodRecordVector_getitemcopy(swigCPtr, index), true);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private LodRecord getitem(int index) {
    LodRecord ret = new LodRecord(PolyVoxCorePINVOKE.LodRecordVector_getitem(swigCPtr, index), false);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, LodRecord val) {
    PolyVoxCorePINVOKE.LodRecordVector_setitem(swigCPtr, index, LodRecord.getCPtr(val));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(LodRecordVector values) {
    PolyVoxCorePINVOKE.LodRecordVector_AddRange(swigCPtr, LodRecordVector.getCPtr(values));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public LodRecordVector GetRange(int index, int count) {
    IntPtr cPtr = PolyVoxCorePINVOKE.LodRecordVector_GetRange(swigCPtr, index, count);
    LodRecordVector ret = (cPtr == IntPtr.Zero) ? null : new LodRecordVector(cPtr, true);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, LodRecord x) {
    PolyVoxCorePINVOKE.LodRecordVector_Insert(swigCPtr, index, LodRecord.getCPtr(x));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, LodRecordVector values) {
    PolyVoxCorePINVOKE.LodRecordVector_InsertRange(swigCPtr, index, LodRecordVector.getCPtr(values));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    PolyVoxCorePINVOKE.LodRecordVector_RemoveAt(swigCPtr, index);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    PolyVoxCorePINVOKE.LodRecordVector_RemoveRange(swigCPtr, index, count);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public static LodRecordVector Repeat(LodRecord value, int count) {
    IntPtr cPtr = PolyVoxCorePINVOKE.LodRecordVector_Repeat(LodRecord.getCPtr(value), count);
    LodRecordVector ret = (cPtr == IntPtr.Zero) ? null : new LodRecordVector(cPtr, true);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    PolyVoxCorePINVOKE.LodRecordVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    PolyVoxCorePINVOKE.LodRecordVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, LodRecordVector values) {
    PolyVoxCorePINVOKE.LodRecordVector_SetRange(swigCPtr, index, LodRecordVector.getCPtr(values));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
