/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace PolyVoxCore {

using System;
using System.Runtime.InteropServices;

public class PositionMaterialNormalVector : IDisposable, System.Collections.IEnumerable
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IEnumerable<PositionMaterialNormal>
#endif
 {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PositionMaterialNormalVector(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PositionMaterialNormalVector obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PositionMaterialNormalVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PolyVoxCorePINVOKE.delete_PositionMaterialNormalVector(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public PositionMaterialNormalVector(System.Collections.ICollection c) : this() {
    if (c == null)
      throw new ArgumentNullException("c");
    foreach (PositionMaterialNormal element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public PositionMaterialNormal this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array)
#else
  public void CopyTo(PositionMaterialNormal[] array)
#endif
  {
    CopyTo(0, array, 0, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array, int arrayIndex)
#else
  public void CopyTo(PositionMaterialNormal[] array, int arrayIndex)
#endif
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(int index, System.Array array, int arrayIndex, int count)
#else
  public void CopyTo(int index, PositionMaterialNormal[] array, int arrayIndex, int count)
#endif
  {
    if (array == null)
      throw new ArgumentNullException("array");
    if (index < 0)
      throw new ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

#if !SWIG_DOTNET_1
  System.Collections.Generic.IEnumerator<PositionMaterialNormal> System.Collections.Generic.IEnumerable<PositionMaterialNormal>.GetEnumerator() {
    return new PositionMaterialNormalVectorEnumerator(this);
  }
#endif

  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return new PositionMaterialNormalVectorEnumerator(this);
  }

  public PositionMaterialNormalVectorEnumerator GetEnumerator() {
    return new PositionMaterialNormalVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class PositionMaterialNormalVectorEnumerator : System.Collections.IEnumerator
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IEnumerator<PositionMaterialNormal>
#endif
  {
    private PositionMaterialNormalVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public PositionMaterialNormalVectorEnumerator(PositionMaterialNormalVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public PositionMaterialNormal Current {
      get {
        if (currentIndex == -1)
          throw new InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new InvalidOperationException("Collection modified.");
        return (PositionMaterialNormal)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new InvalidOperationException("Collection modified.");
      }
    }

#if !SWIG_DOTNET_1
    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
#endif
  }

  public void Clear() {
    PolyVoxCorePINVOKE.PositionMaterialNormalVector_Clear(swigCPtr);
  }

  public void Add(PositionMaterialNormal x) {
    PolyVoxCorePINVOKE.PositionMaterialNormalVector_Add(swigCPtr, PositionMaterialNormal.getCPtr(x));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = PolyVoxCorePINVOKE.PositionMaterialNormalVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = PolyVoxCorePINVOKE.PositionMaterialNormalVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    PolyVoxCorePINVOKE.PositionMaterialNormalVector_reserve(swigCPtr, n);
  }

  public PositionMaterialNormalVector() : this(PolyVoxCorePINVOKE.new_PositionMaterialNormalVector__SWIG_0(), true) {
  }

  public PositionMaterialNormalVector(PositionMaterialNormalVector other) : this(PolyVoxCorePINVOKE.new_PositionMaterialNormalVector__SWIG_1(PositionMaterialNormalVector.getCPtr(other)), true) {
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public PositionMaterialNormalVector(int capacity) : this(PolyVoxCorePINVOKE.new_PositionMaterialNormalVector__SWIG_2(capacity), true) {
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  private PositionMaterialNormal getitemcopy(int index) {
    PositionMaterialNormal ret = new PositionMaterialNormal(PolyVoxCorePINVOKE.PositionMaterialNormalVector_getitemcopy(swigCPtr, index), true);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private PositionMaterialNormal getitem(int index) {
    PositionMaterialNormal ret = new PositionMaterialNormal(PolyVoxCorePINVOKE.PositionMaterialNormalVector_getitem(swigCPtr, index), false);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, PositionMaterialNormal val) {
    PolyVoxCorePINVOKE.PositionMaterialNormalVector_setitem(swigCPtr, index, PositionMaterialNormal.getCPtr(val));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(PositionMaterialNormalVector values) {
    PolyVoxCorePINVOKE.PositionMaterialNormalVector_AddRange(swigCPtr, PositionMaterialNormalVector.getCPtr(values));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public PositionMaterialNormalVector GetRange(int index, int count) {
    IntPtr cPtr = PolyVoxCorePINVOKE.PositionMaterialNormalVector_GetRange(swigCPtr, index, count);
    PositionMaterialNormalVector ret = (cPtr == IntPtr.Zero) ? null : new PositionMaterialNormalVector(cPtr, true);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, PositionMaterialNormal x) {
    PolyVoxCorePINVOKE.PositionMaterialNormalVector_Insert(swigCPtr, index, PositionMaterialNormal.getCPtr(x));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, PositionMaterialNormalVector values) {
    PolyVoxCorePINVOKE.PositionMaterialNormalVector_InsertRange(swigCPtr, index, PositionMaterialNormalVector.getCPtr(values));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    PolyVoxCorePINVOKE.PositionMaterialNormalVector_RemoveAt(swigCPtr, index);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    PolyVoxCorePINVOKE.PositionMaterialNormalVector_RemoveRange(swigCPtr, index, count);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public static PositionMaterialNormalVector Repeat(PositionMaterialNormal value, int count) {
    IntPtr cPtr = PolyVoxCorePINVOKE.PositionMaterialNormalVector_Repeat(PositionMaterialNormal.getCPtr(value), count);
    PositionMaterialNormalVector ret = (cPtr == IntPtr.Zero) ? null : new PositionMaterialNormalVector(cPtr, true);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    PolyVoxCorePINVOKE.PositionMaterialNormalVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    PolyVoxCorePINVOKE.PositionMaterialNormalVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, PositionMaterialNormalVector values) {
    PolyVoxCorePINVOKE.PositionMaterialNormalVector_SetRange(swigCPtr, index, PositionMaterialNormalVector.getCPtr(values));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
