/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace PolyVoxCore {

using System;
using System.Runtime.InteropServices;

public class PositionMaterial : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PositionMaterial(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PositionMaterial obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PositionMaterial() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PolyVoxCorePINVOKE.delete_PositionMaterial(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public PositionMaterial() : this(PolyVoxCorePINVOKE.new_PositionMaterial__SWIG_0(), true) {
  }

  public PositionMaterial(Vector3DFloat positionToSet, float materialToSet) : this(PolyVoxCorePINVOKE.new_PositionMaterial__SWIG_1(Vector3DFloat.getCPtr(positionToSet), materialToSet), true) {
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public float getMaterial() {
    float ret = PolyVoxCorePINVOKE.PositionMaterial_getMaterial(swigCPtr);
    return ret;
  }

  public Vector3DFloat getPosition() {
    Vector3DFloat ret = new Vector3DFloat(PolyVoxCorePINVOKE.PositionMaterial_getPosition(swigCPtr), false);
    return ret;
  }

  public void setMaterial(float materialToSet) {
    PolyVoxCorePINVOKE.PositionMaterial_setMaterial(swigCPtr, materialToSet);
  }

  public void setPosition(Vector3DFloat positionToSet) {
    PolyVoxCorePINVOKE.PositionMaterial_setPosition(swigCPtr, Vector3DFloat.getCPtr(positionToSet));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector3DFloat position {
    set {
      PolyVoxCorePINVOKE.PositionMaterial_position_set(swigCPtr, Vector3DFloat.getCPtr(value));
    } 
    get {
      IntPtr cPtr = PolyVoxCorePINVOKE.PositionMaterial_position_get(swigCPtr);
      Vector3DFloat ret = (cPtr == IntPtr.Zero) ? null : new Vector3DFloat(cPtr, false);
      return ret;
    } 
  }

  public float material {
    set {
      PolyVoxCorePINVOKE.PositionMaterial_material_set(swigCPtr, value);
    } 
    get {
      float ret = PolyVoxCorePINVOKE.PositionMaterial_material_get(swigCPtr);
      return ret;
    } 
  }

}

}
