/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace PolyVoxCore {

using System;
using System.Runtime.InteropServices;

public class uint8Vector : IDisposable, System.Collections.IEnumerable
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IList<byte>
#endif
 {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal uint8Vector(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(uint8Vector obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~uint8Vector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PolyVoxCorePINVOKE.delete_uint8Vector(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public uint8Vector(System.Collections.ICollection c) : this() {
    if (c == null)
      throw new ArgumentNullException("c");
    foreach (byte element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public byte this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array)
#else
  public void CopyTo(byte[] array)
#endif
  {
    CopyTo(0, array, 0, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array, int arrayIndex)
#else
  public void CopyTo(byte[] array, int arrayIndex)
#endif
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(int index, System.Array array, int arrayIndex, int count)
#else
  public void CopyTo(int index, byte[] array, int arrayIndex, int count)
#endif
  {
    if (array == null)
      throw new ArgumentNullException("array");
    if (index < 0)
      throw new ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

#if !SWIG_DOTNET_1
  System.Collections.Generic.IEnumerator<byte> System.Collections.Generic.IEnumerable<byte>.GetEnumerator() {
    return new uint8VectorEnumerator(this);
  }
#endif

  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return new uint8VectorEnumerator(this);
  }

  public uint8VectorEnumerator GetEnumerator() {
    return new uint8VectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class uint8VectorEnumerator : System.Collections.IEnumerator
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IEnumerator<byte>
#endif
  {
    private uint8Vector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public uint8VectorEnumerator(uint8Vector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public byte Current {
      get {
        if (currentIndex == -1)
          throw new InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new InvalidOperationException("Collection modified.");
        return (byte)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new InvalidOperationException("Collection modified.");
      }
    }

#if !SWIG_DOTNET_1
    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
#endif
  }

  public void Clear() {
    PolyVoxCorePINVOKE.uint8Vector_Clear(swigCPtr);
  }

  public void Add(byte x) {
    PolyVoxCorePINVOKE.uint8Vector_Add(swigCPtr, x);
  }

  private uint size() {
    uint ret = PolyVoxCorePINVOKE.uint8Vector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = PolyVoxCorePINVOKE.uint8Vector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    PolyVoxCorePINVOKE.uint8Vector_reserve(swigCPtr, n);
  }

  public uint8Vector() : this(PolyVoxCorePINVOKE.new_uint8Vector__SWIG_0(), true) {
  }

  public uint8Vector(uint8Vector other) : this(PolyVoxCorePINVOKE.new_uint8Vector__SWIG_1(uint8Vector.getCPtr(other)), true) {
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public uint8Vector(int capacity) : this(PolyVoxCorePINVOKE.new_uint8Vector__SWIG_2(capacity), true) {
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  private byte getitemcopy(int index) {
    byte ret = PolyVoxCorePINVOKE.uint8Vector_getitemcopy(swigCPtr, index);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private byte getitem(int index) {
    byte ret = PolyVoxCorePINVOKE.uint8Vector_getitem(swigCPtr, index);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, byte val) {
    PolyVoxCorePINVOKE.uint8Vector_setitem(swigCPtr, index, val);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(uint8Vector values) {
    PolyVoxCorePINVOKE.uint8Vector_AddRange(swigCPtr, uint8Vector.getCPtr(values));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public uint8Vector GetRange(int index, int count) {
    IntPtr cPtr = PolyVoxCorePINVOKE.uint8Vector_GetRange(swigCPtr, index, count);
    uint8Vector ret = (cPtr == IntPtr.Zero) ? null : new uint8Vector(cPtr, true);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, byte x) {
    PolyVoxCorePINVOKE.uint8Vector_Insert(swigCPtr, index, x);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, uint8Vector values) {
    PolyVoxCorePINVOKE.uint8Vector_InsertRange(swigCPtr, index, uint8Vector.getCPtr(values));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    PolyVoxCorePINVOKE.uint8Vector_RemoveAt(swigCPtr, index);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    PolyVoxCorePINVOKE.uint8Vector_RemoveRange(swigCPtr, index, count);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public static uint8Vector Repeat(byte value, int count) {
    IntPtr cPtr = PolyVoxCorePINVOKE.uint8Vector_Repeat(value, count);
    uint8Vector ret = (cPtr == IntPtr.Zero) ? null : new uint8Vector(cPtr, true);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    PolyVoxCorePINVOKE.uint8Vector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    PolyVoxCorePINVOKE.uint8Vector_Reverse__SWIG_1(swigCPtr, index, count);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, uint8Vector values) {
    PolyVoxCorePINVOKE.uint8Vector_SetRange(swigCPtr, index, uint8Vector.getCPtr(values));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(byte value) {
    bool ret = PolyVoxCorePINVOKE.uint8Vector_Contains(swigCPtr, value);
    return ret;
  }

  public int IndexOf(byte value) {
    int ret = PolyVoxCorePINVOKE.uint8Vector_IndexOf(swigCPtr, value);
    return ret;
  }

  public int LastIndexOf(byte value) {
    int ret = PolyVoxCorePINVOKE.uint8Vector_LastIndexOf(swigCPtr, value);
    return ret;
  }

  public bool Remove(byte value) {
    bool ret = PolyVoxCorePINVOKE.uint8Vector_Remove(swigCPtr, value);
    return ret;
  }

}

}
