/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace PolyVoxCore {

using System;
using System.Runtime.InteropServices;

public class Vector3DDouble : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Vector3DDouble(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Vector3DDouble obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Vector3DDouble() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PolyVoxCorePINVOKE.delete_Vector3DDouble(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public Vector3DDouble(double x, double y) : this(PolyVoxCorePINVOKE.new_Vector3DDouble__SWIG_0(x, y), true) {
  }

  public Vector3DDouble(double x, double y, double z) : this(PolyVoxCorePINVOKE.new_Vector3DDouble__SWIG_1(x, y, z), true) {
  }

  public Vector3DDouble(double x, double y, double z, double w) : this(PolyVoxCorePINVOKE.new_Vector3DDouble__SWIG_2(x, y, z, w), true) {
  }

  public Vector3DDouble() : this(PolyVoxCorePINVOKE.new_Vector3DDouble__SWIG_3(), true) {
  }

  public Vector3DDouble(Vector3DDouble vector) : this(PolyVoxCorePINVOKE.new_Vector3DDouble__SWIG_4(Vector3DDouble.getCPtr(vector)), true) {
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector3DDouble Assignment(Vector3DDouble rhs) {
    Vector3DDouble ret = new Vector3DDouble(PolyVoxCorePINVOKE.Vector3DDouble_Assignment(swigCPtr, Vector3DDouble.getCPtr(rhs)), false);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool equals(Vector3DDouble rhs) {
    bool ret = PolyVoxCorePINVOKE.Vector3DDouble_equals(swigCPtr, Vector3DDouble.getCPtr(rhs));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool lessThan(Vector3DDouble rhs) {
    bool ret = PolyVoxCorePINVOKE.Vector3DDouble_lessThan(swigCPtr, Vector3DDouble.getCPtr(rhs));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector3DDouble additionAssignment(Vector3DDouble rhs) {
    Vector3DDouble ret = new Vector3DDouble(PolyVoxCorePINVOKE.Vector3DDouble_additionAssignment(swigCPtr, Vector3DDouble.getCPtr(rhs)), false);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector3DDouble subtractionAssignment(Vector3DDouble rhs) {
    Vector3DDouble ret = new Vector3DDouble(PolyVoxCorePINVOKE.Vector3DDouble_subtractionAssignment(swigCPtr, Vector3DDouble.getCPtr(rhs)), false);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector3DDouble multiplicationAssignment(double rhs) {
    Vector3DDouble ret = new Vector3DDouble(PolyVoxCorePINVOKE.Vector3DDouble_multiplicationAssignment(swigCPtr, rhs), false);
    return ret;
  }

  public Vector3DDouble divisionAssignment(double rhs) {
    Vector3DDouble ret = new Vector3DDouble(PolyVoxCorePINVOKE.Vector3DDouble_divisionAssignment(swigCPtr, rhs), false);
    return ret;
  }

  public double getElement(uint index) {
    double ret = PolyVoxCorePINVOKE.Vector3DDouble_getElement(swigCPtr, index);
    return ret;
  }

  public double getX() {
    double ret = PolyVoxCorePINVOKE.Vector3DDouble_getX(swigCPtr);
    return ret;
  }

  public double getY() {
    double ret = PolyVoxCorePINVOKE.Vector3DDouble_getY(swigCPtr);
    return ret;
  }

  public double getZ() {
    double ret = PolyVoxCorePINVOKE.Vector3DDouble_getZ(swigCPtr);
    return ret;
  }

  public double getW() {
    double ret = PolyVoxCorePINVOKE.Vector3DDouble_getW(swigCPtr);
    return ret;
  }

  public void setElement(uint index, double tValue) {
    PolyVoxCorePINVOKE.Vector3DDouble_setElement(swigCPtr, index, tValue);
  }

  public void setElements(double x, double y) {
    PolyVoxCorePINVOKE.Vector3DDouble_setElements__SWIG_0(swigCPtr, x, y);
  }

  public void setElements(double x, double y, double z) {
    PolyVoxCorePINVOKE.Vector3DDouble_setElements__SWIG_1(swigCPtr, x, y, z);
  }

  public void setElements(double x, double y, double z, double w) {
    PolyVoxCorePINVOKE.Vector3DDouble_setElements__SWIG_2(swigCPtr, x, y, z, w);
  }

  public void setX(double tX) {
    PolyVoxCorePINVOKE.Vector3DDouble_setX(swigCPtr, tX);
  }

  public void setY(double tY) {
    PolyVoxCorePINVOKE.Vector3DDouble_setY(swigCPtr, tY);
  }

  public void setZ(double tZ) {
    PolyVoxCorePINVOKE.Vector3DDouble_setZ(swigCPtr, tZ);
  }

  public void setW(double tW) {
    PolyVoxCorePINVOKE.Vector3DDouble_setW(swigCPtr, tW);
  }

  public double length() {
    double ret = PolyVoxCorePINVOKE.Vector3DDouble_length(swigCPtr);
    return ret;
  }

  public double lengthSquared() {
    double ret = PolyVoxCorePINVOKE.Vector3DDouble_lengthSquared(swigCPtr);
    return ret;
  }

  public double angleTo(Vector3DDouble vector) {
    double ret = PolyVoxCorePINVOKE.Vector3DDouble_angleTo(swigCPtr, Vector3DDouble.getCPtr(vector));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector3DDouble cross(Vector3DDouble vector) {
    Vector3DDouble ret = new Vector3DDouble(PolyVoxCorePINVOKE.Vector3DDouble_cross(swigCPtr, Vector3DDouble.getCPtr(vector)), true);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double dot(Vector3DDouble rhs) {
    double ret = PolyVoxCorePINVOKE.Vector3DDouble_dot(swigCPtr, Vector3DDouble.getCPtr(rhs));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void normalise() {
    PolyVoxCorePINVOKE.Vector3DDouble_normalise(swigCPtr);
  }

}

}
