/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace PolyVoxCore {

using System;
using System.Runtime.InteropServices;

public class Vector3DUint32 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Vector3DUint32(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Vector3DUint32 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Vector3DUint32() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PolyVoxCorePINVOKE.delete_Vector3DUint32(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public Vector3DUint32(uint x, uint y) : this(PolyVoxCorePINVOKE.new_Vector3DUint32__SWIG_0(x, y), true) {
  }

  public Vector3DUint32(uint x, uint y, uint z) : this(PolyVoxCorePINVOKE.new_Vector3DUint32__SWIG_1(x, y, z), true) {
  }

  public Vector3DUint32(uint x, uint y, uint z, uint w) : this(PolyVoxCorePINVOKE.new_Vector3DUint32__SWIG_2(x, y, z, w), true) {
  }

  public Vector3DUint32() : this(PolyVoxCorePINVOKE.new_Vector3DUint32__SWIG_3(), true) {
  }

  public Vector3DUint32(Vector3DUint32 vector) : this(PolyVoxCorePINVOKE.new_Vector3DUint32__SWIG_4(Vector3DUint32.getCPtr(vector)), true) {
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector3DUint32 Assignment(Vector3DUint32 rhs) {
    Vector3DUint32 ret = new Vector3DUint32(PolyVoxCorePINVOKE.Vector3DUint32_Assignment(swigCPtr, Vector3DUint32.getCPtr(rhs)), false);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool equals(Vector3DUint32 rhs) {
    bool ret = PolyVoxCorePINVOKE.Vector3DUint32_equals(swigCPtr, Vector3DUint32.getCPtr(rhs));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool lessThan(Vector3DUint32 rhs) {
    bool ret = PolyVoxCorePINVOKE.Vector3DUint32_lessThan(swigCPtr, Vector3DUint32.getCPtr(rhs));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector3DUint32 additionAssignment(Vector3DUint32 rhs) {
    Vector3DUint32 ret = new Vector3DUint32(PolyVoxCorePINVOKE.Vector3DUint32_additionAssignment(swigCPtr, Vector3DUint32.getCPtr(rhs)), false);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector3DUint32 subtractionAssignment(Vector3DUint32 rhs) {
    Vector3DUint32 ret = new Vector3DUint32(PolyVoxCorePINVOKE.Vector3DUint32_subtractionAssignment(swigCPtr, Vector3DUint32.getCPtr(rhs)), false);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector3DUint32 multiplicationAssignment(uint rhs) {
    Vector3DUint32 ret = new Vector3DUint32(PolyVoxCorePINVOKE.Vector3DUint32_multiplicationAssignment(swigCPtr, rhs), false);
    return ret;
  }

  public Vector3DUint32 divisionAssignment(uint rhs) {
    Vector3DUint32 ret = new Vector3DUint32(PolyVoxCorePINVOKE.Vector3DUint32_divisionAssignment(swigCPtr, rhs), false);
    return ret;
  }

  public uint getElement(uint index) {
    uint ret = PolyVoxCorePINVOKE.Vector3DUint32_getElement(swigCPtr, index);
    return ret;
  }

  public uint getX() {
    uint ret = PolyVoxCorePINVOKE.Vector3DUint32_getX(swigCPtr);
    return ret;
  }

  public uint getY() {
    uint ret = PolyVoxCorePINVOKE.Vector3DUint32_getY(swigCPtr);
    return ret;
  }

  public uint getZ() {
    uint ret = PolyVoxCorePINVOKE.Vector3DUint32_getZ(swigCPtr);
    return ret;
  }

  public uint getW() {
    uint ret = PolyVoxCorePINVOKE.Vector3DUint32_getW(swigCPtr);
    return ret;
  }

  public void setElement(uint index, uint tValue) {
    PolyVoxCorePINVOKE.Vector3DUint32_setElement(swigCPtr, index, tValue);
  }

  public void setElements(uint x, uint y) {
    PolyVoxCorePINVOKE.Vector3DUint32_setElements__SWIG_0(swigCPtr, x, y);
  }

  public void setElements(uint x, uint y, uint z) {
    PolyVoxCorePINVOKE.Vector3DUint32_setElements__SWIG_1(swigCPtr, x, y, z);
  }

  public void setElements(uint x, uint y, uint z, uint w) {
    PolyVoxCorePINVOKE.Vector3DUint32_setElements__SWIG_2(swigCPtr, x, y, z, w);
  }

  public void setX(uint tX) {
    PolyVoxCorePINVOKE.Vector3DUint32_setX(swigCPtr, tX);
  }

  public void setY(uint tY) {
    PolyVoxCorePINVOKE.Vector3DUint32_setY(swigCPtr, tY);
  }

  public void setZ(uint tZ) {
    PolyVoxCorePINVOKE.Vector3DUint32_setZ(swigCPtr, tZ);
  }

  public void setW(uint tW) {
    PolyVoxCorePINVOKE.Vector3DUint32_setW(swigCPtr, tW);
  }

  public double length() {
    double ret = PolyVoxCorePINVOKE.Vector3DUint32_length(swigCPtr);
    return ret;
  }

  public double lengthSquared() {
    double ret = PolyVoxCorePINVOKE.Vector3DUint32_lengthSquared(swigCPtr);
    return ret;
  }

  public double angleTo(Vector3DUint32 vector) {
    double ret = PolyVoxCorePINVOKE.Vector3DUint32_angleTo(swigCPtr, Vector3DUint32.getCPtr(vector));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector3DUint32 cross(Vector3DUint32 vector) {
    Vector3DUint32 ret = new Vector3DUint32(PolyVoxCorePINVOKE.Vector3DUint32_cross(swigCPtr, Vector3DUint32.getCPtr(vector)), true);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint dot(Vector3DUint32 rhs) {
    uint ret = PolyVoxCorePINVOKE.Vector3DUint32_dot(swigCPtr, Vector3DUint32.getCPtr(rhs));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void normalise() {
    PolyVoxCorePINVOKE.Vector3DUint32_normalise(swigCPtr);
  }

}

}
