/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace PolyVoxCore {

using System;
using System.Runtime.InteropServices;

public class Vector3DFloat : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Vector3DFloat(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Vector3DFloat obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Vector3DFloat() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PolyVoxCorePINVOKE.delete_Vector3DFloat(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public Vector3DFloat(float x, float y) : this(PolyVoxCorePINVOKE.new_Vector3DFloat__SWIG_0(x, y), true) {
  }

  public Vector3DFloat(float x, float y, float z) : this(PolyVoxCorePINVOKE.new_Vector3DFloat__SWIG_1(x, y, z), true) {
  }

  public Vector3DFloat(float x, float y, float z, float w) : this(PolyVoxCorePINVOKE.new_Vector3DFloat__SWIG_2(x, y, z, w), true) {
  }

  public Vector3DFloat() : this(PolyVoxCorePINVOKE.new_Vector3DFloat__SWIG_3(), true) {
  }

  public Vector3DFloat(Vector3DFloat vector) : this(PolyVoxCorePINVOKE.new_Vector3DFloat__SWIG_4(Vector3DFloat.getCPtr(vector)), true) {
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector3DFloat Assignment(Vector3DFloat rhs) {
    Vector3DFloat ret = new Vector3DFloat(PolyVoxCorePINVOKE.Vector3DFloat_Assignment(swigCPtr, Vector3DFloat.getCPtr(rhs)), false);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool equals(Vector3DFloat rhs) {
    bool ret = PolyVoxCorePINVOKE.Vector3DFloat_equals(swigCPtr, Vector3DFloat.getCPtr(rhs));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool lessThan(Vector3DFloat rhs) {
    bool ret = PolyVoxCorePINVOKE.Vector3DFloat_lessThan(swigCPtr, Vector3DFloat.getCPtr(rhs));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector3DFloat additionAssignment(Vector3DFloat rhs) {
    Vector3DFloat ret = new Vector3DFloat(PolyVoxCorePINVOKE.Vector3DFloat_additionAssignment(swigCPtr, Vector3DFloat.getCPtr(rhs)), false);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector3DFloat subtractionAssignment(Vector3DFloat rhs) {
    Vector3DFloat ret = new Vector3DFloat(PolyVoxCorePINVOKE.Vector3DFloat_subtractionAssignment(swigCPtr, Vector3DFloat.getCPtr(rhs)), false);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector3DFloat multiplicationAssignment(float rhs) {
    Vector3DFloat ret = new Vector3DFloat(PolyVoxCorePINVOKE.Vector3DFloat_multiplicationAssignment(swigCPtr, rhs), false);
    return ret;
  }

  public Vector3DFloat divisionAssignment(float rhs) {
    Vector3DFloat ret = new Vector3DFloat(PolyVoxCorePINVOKE.Vector3DFloat_divisionAssignment(swigCPtr, rhs), false);
    return ret;
  }

  public float getElement(uint index) {
    float ret = PolyVoxCorePINVOKE.Vector3DFloat_getElement(swigCPtr, index);
    return ret;
  }

  public float getX() {
    float ret = PolyVoxCorePINVOKE.Vector3DFloat_getX(swigCPtr);
    return ret;
  }

  public float getY() {
    float ret = PolyVoxCorePINVOKE.Vector3DFloat_getY(swigCPtr);
    return ret;
  }

  public float getZ() {
    float ret = PolyVoxCorePINVOKE.Vector3DFloat_getZ(swigCPtr);
    return ret;
  }

  public float getW() {
    float ret = PolyVoxCorePINVOKE.Vector3DFloat_getW(swigCPtr);
    return ret;
  }

  public void setElement(uint index, float tValue) {
    PolyVoxCorePINVOKE.Vector3DFloat_setElement(swigCPtr, index, tValue);
  }

  public void setElements(float x, float y) {
    PolyVoxCorePINVOKE.Vector3DFloat_setElements__SWIG_0(swigCPtr, x, y);
  }

  public void setElements(float x, float y, float z) {
    PolyVoxCorePINVOKE.Vector3DFloat_setElements__SWIG_1(swigCPtr, x, y, z);
  }

  public void setElements(float x, float y, float z, float w) {
    PolyVoxCorePINVOKE.Vector3DFloat_setElements__SWIG_2(swigCPtr, x, y, z, w);
  }

  public void setX(float tX) {
    PolyVoxCorePINVOKE.Vector3DFloat_setX(swigCPtr, tX);
  }

  public void setY(float tY) {
    PolyVoxCorePINVOKE.Vector3DFloat_setY(swigCPtr, tY);
  }

  public void setZ(float tZ) {
    PolyVoxCorePINVOKE.Vector3DFloat_setZ(swigCPtr, tZ);
  }

  public void setW(float tW) {
    PolyVoxCorePINVOKE.Vector3DFloat_setW(swigCPtr, tW);
  }

  public double length() {
    double ret = PolyVoxCorePINVOKE.Vector3DFloat_length(swigCPtr);
    return ret;
  }

  public double lengthSquared() {
    double ret = PolyVoxCorePINVOKE.Vector3DFloat_lengthSquared(swigCPtr);
    return ret;
  }

  public double angleTo(Vector3DFloat vector) {
    double ret = PolyVoxCorePINVOKE.Vector3DFloat_angleTo(swigCPtr, Vector3DFloat.getCPtr(vector));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector3DFloat cross(Vector3DFloat vector) {
    Vector3DFloat ret = new Vector3DFloat(PolyVoxCorePINVOKE.Vector3DFloat_cross(swigCPtr, Vector3DFloat.getCPtr(vector)), true);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float dot(Vector3DFloat rhs) {
    float ret = PolyVoxCorePINVOKE.Vector3DFloat_dot(swigCPtr, Vector3DFloat.getCPtr(rhs));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void normalise() {
    PolyVoxCorePINVOKE.Vector3DFloat_normalise(swigCPtr);
  }

}

}
