/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace PolyVoxCore {

using System;
using System.Runtime.InteropServices;

public class Vector3DInt8 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Vector3DInt8(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Vector3DInt8 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Vector3DInt8() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PolyVoxCorePINVOKE.delete_Vector3DInt8(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public Vector3DInt8(sbyte x, sbyte y) : this(PolyVoxCorePINVOKE.new_Vector3DInt8__SWIG_0(x, y), true) {
  }

  public Vector3DInt8(sbyte x, sbyte y, sbyte z) : this(PolyVoxCorePINVOKE.new_Vector3DInt8__SWIG_1(x, y, z), true) {
  }

  public Vector3DInt8(sbyte x, sbyte y, sbyte z, sbyte w) : this(PolyVoxCorePINVOKE.new_Vector3DInt8__SWIG_2(x, y, z, w), true) {
  }

  public Vector3DInt8() : this(PolyVoxCorePINVOKE.new_Vector3DInt8__SWIG_3(), true) {
  }

  public Vector3DInt8(Vector3DInt8 vector) : this(PolyVoxCorePINVOKE.new_Vector3DInt8__SWIG_4(Vector3DInt8.getCPtr(vector)), true) {
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector3DInt8 Assignment(Vector3DInt8 rhs) {
    Vector3DInt8 ret = new Vector3DInt8(PolyVoxCorePINVOKE.Vector3DInt8_Assignment(swigCPtr, Vector3DInt8.getCPtr(rhs)), false);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool equals(Vector3DInt8 rhs) {
    bool ret = PolyVoxCorePINVOKE.Vector3DInt8_equals(swigCPtr, Vector3DInt8.getCPtr(rhs));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool lessThan(Vector3DInt8 rhs) {
    bool ret = PolyVoxCorePINVOKE.Vector3DInt8_lessThan(swigCPtr, Vector3DInt8.getCPtr(rhs));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector3DInt8 additionAssignment(Vector3DInt8 rhs) {
    Vector3DInt8 ret = new Vector3DInt8(PolyVoxCorePINVOKE.Vector3DInt8_additionAssignment(swigCPtr, Vector3DInt8.getCPtr(rhs)), false);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector3DInt8 subtractionAssignment(Vector3DInt8 rhs) {
    Vector3DInt8 ret = new Vector3DInt8(PolyVoxCorePINVOKE.Vector3DInt8_subtractionAssignment(swigCPtr, Vector3DInt8.getCPtr(rhs)), false);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector3DInt8 multiplicationAssignment(sbyte rhs) {
    Vector3DInt8 ret = new Vector3DInt8(PolyVoxCorePINVOKE.Vector3DInt8_multiplicationAssignment(swigCPtr, rhs), false);
    return ret;
  }

  public Vector3DInt8 divisionAssignment(sbyte rhs) {
    Vector3DInt8 ret = new Vector3DInt8(PolyVoxCorePINVOKE.Vector3DInt8_divisionAssignment(swigCPtr, rhs), false);
    return ret;
  }

  public sbyte getElement(uint index) {
    sbyte ret = PolyVoxCorePINVOKE.Vector3DInt8_getElement(swigCPtr, index);
    return ret;
  }

  public sbyte getX() {
    sbyte ret = PolyVoxCorePINVOKE.Vector3DInt8_getX(swigCPtr);
    return ret;
  }

  public sbyte getY() {
    sbyte ret = PolyVoxCorePINVOKE.Vector3DInt8_getY(swigCPtr);
    return ret;
  }

  public sbyte getZ() {
    sbyte ret = PolyVoxCorePINVOKE.Vector3DInt8_getZ(swigCPtr);
    return ret;
  }

  public sbyte getW() {
    sbyte ret = PolyVoxCorePINVOKE.Vector3DInt8_getW(swigCPtr);
    return ret;
  }

  public void setElement(uint index, sbyte tValue) {
    PolyVoxCorePINVOKE.Vector3DInt8_setElement(swigCPtr, index, tValue);
  }

  public void setElements(sbyte x, sbyte y) {
    PolyVoxCorePINVOKE.Vector3DInt8_setElements__SWIG_0(swigCPtr, x, y);
  }

  public void setElements(sbyte x, sbyte y, sbyte z) {
    PolyVoxCorePINVOKE.Vector3DInt8_setElements__SWIG_1(swigCPtr, x, y, z);
  }

  public void setElements(sbyte x, sbyte y, sbyte z, sbyte w) {
    PolyVoxCorePINVOKE.Vector3DInt8_setElements__SWIG_2(swigCPtr, x, y, z, w);
  }

  public void setX(sbyte tX) {
    PolyVoxCorePINVOKE.Vector3DInt8_setX(swigCPtr, tX);
  }

  public void setY(sbyte tY) {
    PolyVoxCorePINVOKE.Vector3DInt8_setY(swigCPtr, tY);
  }

  public void setZ(sbyte tZ) {
    PolyVoxCorePINVOKE.Vector3DInt8_setZ(swigCPtr, tZ);
  }

  public void setW(sbyte tW) {
    PolyVoxCorePINVOKE.Vector3DInt8_setW(swigCPtr, tW);
  }

  public double length() {
    double ret = PolyVoxCorePINVOKE.Vector3DInt8_length(swigCPtr);
    return ret;
  }

  public double lengthSquared() {
    double ret = PolyVoxCorePINVOKE.Vector3DInt8_lengthSquared(swigCPtr);
    return ret;
  }

  public double angleTo(Vector3DInt8 vector) {
    double ret = PolyVoxCorePINVOKE.Vector3DInt8_angleTo(swigCPtr, Vector3DInt8.getCPtr(vector));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Vector3DInt8 cross(Vector3DInt8 vector) {
    Vector3DInt8 ret = new Vector3DInt8(PolyVoxCorePINVOKE.Vector3DInt8_cross(swigCPtr, Vector3DInt8.getCPtr(vector)), true);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public sbyte dot(Vector3DInt8 rhs) {
    sbyte ret = PolyVoxCorePINVOKE.Vector3DInt8_dot(swigCPtr, Vector3DInt8.getCPtr(rhs));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void normalise() {
    PolyVoxCorePINVOKE.Vector3DInt8_normalise(swigCPtr);
  }

}

}
