/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace PolyVoxCore {

using System;
using System.Runtime.InteropServices;

public class VolumeDensity8 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VolumeDensity8(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(VolumeDensity8 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~VolumeDensity8() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PolyVoxCorePINVOKE.delete_VolumeDensity8(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public VolumeDensity8(ushort uWidth, ushort uHeight, ushort uDepth, ushort uBlockSideLength) : this(PolyVoxCorePINVOKE.new_VolumeDensity8__SWIG_0(uWidth, uHeight, uDepth, uBlockSideLength), true) {
  }

  public VolumeDensity8(ushort uWidth, ushort uHeight, ushort uDepth) : this(PolyVoxCorePINVOKE.new_VolumeDensity8__SWIG_1(uWidth, uHeight, uDepth), true) {
  }

  public Density8 getBorderValue() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeDensity8_getBorderValue(swigCPtr), true);
    return ret;
  }

  public Region getEnclosingRegion() {
    Region ret = new Region(PolyVoxCorePINVOKE.VolumeDensity8_getEnclosingRegion(swigCPtr), true);
    return ret;
  }

  public ushort getWidth() {
    ushort ret = PolyVoxCorePINVOKE.VolumeDensity8_getWidth(swigCPtr);
    return ret;
  }

  public ushort getHeight() {
    ushort ret = PolyVoxCorePINVOKE.VolumeDensity8_getHeight(swigCPtr);
    return ret;
  }

  public ushort getDepth() {
    ushort ret = PolyVoxCorePINVOKE.VolumeDensity8_getDepth(swigCPtr);
    return ret;
  }

  public ushort getLongestSideLength() {
    ushort ret = PolyVoxCorePINVOKE.VolumeDensity8_getLongestSideLength(swigCPtr);
    return ret;
  }

  public ushort getShortestSideLength() {
    ushort ret = PolyVoxCorePINVOKE.VolumeDensity8_getShortestSideLength(swigCPtr);
    return ret;
  }

  public float getDiagonalLength() {
    float ret = PolyVoxCorePINVOKE.VolumeDensity8_getDiagonalLength(swigCPtr);
    return ret;
  }

  public Density8 getVoxelAt(ushort uXPos, ushort uYPos, ushort uZPos) {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeDensity8_getVoxelAt__SWIG_0(swigCPtr, uXPos, uYPos, uZPos), true);
    return ret;
  }

  public Density8 getVoxelAt(Vector3DUint16 v3dPos) {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeDensity8_getVoxelAt__SWIG_1(swigCPtr, Vector3DUint16.getCPtr(v3dPos)), true);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setBorderValue(Density8 tBorder) {
    PolyVoxCorePINVOKE.VolumeDensity8_setBorderValue(swigCPtr, Density8.getCPtr(tBorder));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool setVoxelAt(ushort uXPos, ushort uYPos, ushort uZPos, Density8 tValue) {
    bool ret = PolyVoxCorePINVOKE.VolumeDensity8_setVoxelAt__SWIG_0(swigCPtr, uXPos, uYPos, uZPos, Density8.getCPtr(tValue));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool setVoxelAt(Vector3DUint16 v3dPos, Density8 tValue) {
    bool ret = PolyVoxCorePINVOKE.VolumeDensity8_setVoxelAt__SWIG_1(swigCPtr, Vector3DUint16.getCPtr(v3dPos), Density8.getCPtr(tValue));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void resize(ushort uWidth, ushort uHeight, ushort uDepth, ushort uBlockSideLength) {
    PolyVoxCorePINVOKE.VolumeDensity8_resize__SWIG_0(swigCPtr, uWidth, uHeight, uDepth, uBlockSideLength);
  }

  public void resize(ushort uWidth, ushort uHeight, ushort uDepth) {
    PolyVoxCorePINVOKE.VolumeDensity8_resize__SWIG_1(swigCPtr, uWidth, uHeight, uDepth);
  }

  public void tidyUpMemory(uint uNoOfBlocksToProcess) {
    PolyVoxCorePINVOKE.VolumeDensity8_tidyUpMemory__SWIG_0(swigCPtr, uNoOfBlocksToProcess);
  }

  public void tidyUpMemory() {
    PolyVoxCorePINVOKE.VolumeDensity8_tidyUpMemory__SWIG_1(swigCPtr);
  }

}

}
