/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace PolyVoxCore {

using System;
using System.Runtime.InteropServices;

public class VolumeSamplerDensity8 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VolumeSamplerDensity8(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(VolumeSamplerDensity8 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~VolumeSamplerDensity8() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PolyVoxCorePINVOKE.delete_VolumeSamplerDensity8(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public VolumeSamplerDensity8(VolumeDensity8 volume) : this(PolyVoxCorePINVOKE.new_VolumeSamplerDensity8(VolumeDensity8.getCPtr(volume)), true) {
  }

  public VolumeSamplerDensity8 Assignment(VolumeSamplerDensity8 rhs) {
    VolumeSamplerDensity8 ret = new VolumeSamplerDensity8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_Assignment(swigCPtr, VolumeSamplerDensity8.getCPtr(rhs)), false);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ushort getPosX() {
    ushort ret = PolyVoxCorePINVOKE.VolumeSamplerDensity8_getPosX(swigCPtr);
    return ret;
  }

  public ushort getPosY() {
    ushort ret = PolyVoxCorePINVOKE.VolumeSamplerDensity8_getPosY(swigCPtr);
    return ret;
  }

  public ushort getPosZ() {
    ushort ret = PolyVoxCorePINVOKE.VolumeSamplerDensity8_getPosZ(swigCPtr);
    return ret;
  }

  public Density8 getSubSampledVoxel(byte uLevel) {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_getSubSampledVoxel(swigCPtr, uLevel), true);
    return ret;
  }

  public VolumeDensity8 getVolume() {
    IntPtr cPtr = PolyVoxCorePINVOKE.VolumeSamplerDensity8_getVolume(swigCPtr);
    VolumeDensity8 ret = (cPtr == IntPtr.Zero) ? null : new VolumeDensity8(cPtr, false);
    return ret;
  }

  public Density8 getVoxel() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_getVoxel(swigCPtr), true);
    return ret;
  }

  public void setPosition(Vector3DInt16 v3dNewPos) {
    PolyVoxCorePINVOKE.VolumeSamplerDensity8_setPosition__SWIG_0(swigCPtr, Vector3DInt16.getCPtr(v3dNewPos));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void setPosition(ushort xPos, ushort yPos, ushort zPos) {
    PolyVoxCorePINVOKE.VolumeSamplerDensity8_setPosition__SWIG_1(swigCPtr, xPos, yPos, zPos);
  }

  public void movePositiveX() {
    PolyVoxCorePINVOKE.VolumeSamplerDensity8_movePositiveX(swigCPtr);
  }

  public void movePositiveY() {
    PolyVoxCorePINVOKE.VolumeSamplerDensity8_movePositiveY(swigCPtr);
  }

  public void movePositiveZ() {
    PolyVoxCorePINVOKE.VolumeSamplerDensity8_movePositiveZ(swigCPtr);
  }

  public void moveNegativeX() {
    PolyVoxCorePINVOKE.VolumeSamplerDensity8_moveNegativeX(swigCPtr);
  }

  public void moveNegativeY() {
    PolyVoxCorePINVOKE.VolumeSamplerDensity8_moveNegativeY(swigCPtr);
  }

  public void moveNegativeZ() {
    PolyVoxCorePINVOKE.VolumeSamplerDensity8_moveNegativeZ(swigCPtr);
  }

  public Density8 peekVoxel1nx1ny1nz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel1nx1ny1nz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel1nx1ny0pz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel1nx1ny0pz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel1nx1ny1pz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel1nx1ny1pz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel1nx0py1nz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel1nx0py1nz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel1nx0py0pz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel1nx0py0pz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel1nx0py1pz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel1nx0py1pz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel1nx1py1nz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel1nx1py1nz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel1nx1py0pz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel1nx1py0pz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel1nx1py1pz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel1nx1py1pz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel0px1ny1nz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel0px1ny1nz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel0px1ny0pz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel0px1ny0pz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel0px1ny1pz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel0px1ny1pz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel0px0py1nz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel0px0py1nz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel0px0py0pz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel0px0py0pz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel0px0py1pz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel0px0py1pz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel0px1py1nz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel0px1py1nz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel0px1py0pz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel0px1py0pz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel0px1py1pz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel0px1py1pz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel1px1ny1nz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel1px1ny1nz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel1px1ny0pz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel1px1ny0pz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel1px1ny1pz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel1px1ny1pz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel1px0py1nz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel1px0py1nz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel1px0py0pz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel1px0py0pz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel1px0py1pz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel1px0py1pz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel1px1py1nz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel1px1py1nz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel1px1py0pz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel1px1py0pz(swigCPtr), true);
    return ret;
  }

  public Density8 peekVoxel1px1py1pz() {
    Density8 ret = new Density8(PolyVoxCorePINVOKE.VolumeSamplerDensity8_peekVoxel1px1py1pz(swigCPtr), true);
    return ret;
  }

}

}
