/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace PolyVoxCore {

using System;
using System.Runtime.InteropServices;

public class VolumeSamplerMaterial8 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VolumeSamplerMaterial8(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(VolumeSamplerMaterial8 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~VolumeSamplerMaterial8() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PolyVoxCorePINVOKE.delete_VolumeSamplerMaterial8(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public VolumeSamplerMaterial8(VolumeMaterial8 volume) : this(PolyVoxCorePINVOKE.new_VolumeSamplerMaterial8(VolumeMaterial8.getCPtr(volume)), true) {
  }

  public VolumeSamplerMaterial8 Assignment(VolumeSamplerMaterial8 rhs) {
    VolumeSamplerMaterial8 ret = new VolumeSamplerMaterial8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_Assignment(swigCPtr, VolumeSamplerMaterial8.getCPtr(rhs)), false);
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ushort getPosX() {
    ushort ret = PolyVoxCorePINVOKE.VolumeSamplerMaterial8_getPosX(swigCPtr);
    return ret;
  }

  public ushort getPosY() {
    ushort ret = PolyVoxCorePINVOKE.VolumeSamplerMaterial8_getPosY(swigCPtr);
    return ret;
  }

  public ushort getPosZ() {
    ushort ret = PolyVoxCorePINVOKE.VolumeSamplerMaterial8_getPosZ(swigCPtr);
    return ret;
  }

  public Material8 getSubSampledVoxel(byte uLevel) {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_getSubSampledVoxel(swigCPtr, uLevel), true);
    return ret;
  }

  public VolumeMaterial8 getVolume() {
    IntPtr cPtr = PolyVoxCorePINVOKE.VolumeSamplerMaterial8_getVolume(swigCPtr);
    VolumeMaterial8 ret = (cPtr == IntPtr.Zero) ? null : new VolumeMaterial8(cPtr, false);
    return ret;
  }

  public Material8 getVoxel() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_getVoxel(swigCPtr), true);
    return ret;
  }

  public void setPosition(Vector3DInt16 v3dNewPos) {
    PolyVoxCorePINVOKE.VolumeSamplerMaterial8_setPosition__SWIG_0(swigCPtr, Vector3DInt16.getCPtr(v3dNewPos));
    if (PolyVoxCorePINVOKE.SWIGPendingException.Pending) throw PolyVoxCorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void setPosition(ushort xPos, ushort yPos, ushort zPos) {
    PolyVoxCorePINVOKE.VolumeSamplerMaterial8_setPosition__SWIG_1(swigCPtr, xPos, yPos, zPos);
  }

  public void movePositiveX() {
    PolyVoxCorePINVOKE.VolumeSamplerMaterial8_movePositiveX(swigCPtr);
  }

  public void movePositiveY() {
    PolyVoxCorePINVOKE.VolumeSamplerMaterial8_movePositiveY(swigCPtr);
  }

  public void movePositiveZ() {
    PolyVoxCorePINVOKE.VolumeSamplerMaterial8_movePositiveZ(swigCPtr);
  }

  public void moveNegativeX() {
    PolyVoxCorePINVOKE.VolumeSamplerMaterial8_moveNegativeX(swigCPtr);
  }

  public void moveNegativeY() {
    PolyVoxCorePINVOKE.VolumeSamplerMaterial8_moveNegativeY(swigCPtr);
  }

  public void moveNegativeZ() {
    PolyVoxCorePINVOKE.VolumeSamplerMaterial8_moveNegativeZ(swigCPtr);
  }

  public Material8 peekVoxel1nx1ny1nz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel1nx1ny1nz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel1nx1ny0pz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel1nx1ny0pz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel1nx1ny1pz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel1nx1ny1pz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel1nx0py1nz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel1nx0py1nz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel1nx0py0pz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel1nx0py0pz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel1nx0py1pz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel1nx0py1pz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel1nx1py1nz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel1nx1py1nz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel1nx1py0pz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel1nx1py0pz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel1nx1py1pz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel1nx1py1pz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel0px1ny1nz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel0px1ny1nz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel0px1ny0pz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel0px1ny0pz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel0px1ny1pz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel0px1ny1pz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel0px0py1nz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel0px0py1nz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel0px0py0pz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel0px0py0pz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel0px0py1pz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel0px0py1pz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel0px1py1nz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel0px1py1nz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel0px1py0pz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel0px1py0pz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel0px1py1pz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel0px1py1pz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel1px1ny1nz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel1px1ny1nz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel1px1ny0pz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel1px1ny0pz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel1px1ny1pz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel1px1ny1pz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel1px0py1nz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel1px0py1nz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel1px0py0pz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel1px0py0pz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel1px0py1pz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel1px0py1pz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel1px1py1nz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel1px1py1nz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel1px1py0pz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel1px1py0pz(swigCPtr), true);
    return ret;
  }

  public Material8 peekVoxel1px1py1pz() {
    Material8 ret = new Material8(PolyVoxCorePINVOKE.VolumeSamplerMaterial8_peekVoxel1px1py1pz(swigCPtr), true);
    return ret;
  }

}

}
